version: "3.3"

services:
  database:
    image: postgres
    container_name: postgres_con
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
  backend:
    image: backend
    build: ./backend_app
    container_name: backend_container
    ports:
      - 8089:8089
    links:
      - database
    depends_on:
      - database
  frontend:
    image: frontend
    build: ./frontend_app
    container_name: frontend_container
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres:
